# Уникальный ключ проекта в локальном SonarQube.
sonar.projectKey=kafka-adapter
sonar.projectName=1С: Адаптер Kafka

# Исходники EDT лежат в src. Пути задаются относительно этого файла.
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.inclusions=**/*.bsl

# Настройки sonar-bsl-plugin-community.
sonar.bsl.file.suffixes=.bsl
sonar.bsl.languageserver.enabled=true
sonar.bsl.languageserver.diagnosticLanguage=ru
sonar.bsl.languageserver.skipSupport=never
