# Параметры анализа исходного кода 1С.
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.inclusions=**/*.bsl
sonar.coverageReportPaths=assets/unit/genericCoverage.xml,assets/ui/genericCoverage.xml

# Использовать конфигурацию BSL Language Server из репозитория.
sonar.bsl.languageserver.enabled=true
sonar.bsl.languageserver.overrideConfiguration=true
sonar.bsl.languageserver.configurationPath=.bsl-language-server.json
