name: Build & Release

on:
  # GitHub Actions не запускает release.created для draft-релизов.
  release:
    types: [published]

permissions:
  actions: read
  checks: write
  contents: write
  packages: read

jobs:
  build_cf_xml:
    name: Build CF-XML
    uses: ./.github/workflows/release-build-cf-xml.yml
    secrets: inherit

  tests:
    name: Tests
    needs: [build_cf_xml]
    uses: ./.github/workflows/release-tests.yml
    secrets: inherit

  build_cf:
    name: Build CF
    needs: [tests]
    uses: ./.github/workflows/release-build-cf.yml
    secrets: inherit

  build_cfe:
    name: Build CFE
    needs: [tests]
    uses: ./.github/workflows/release-build-cfe.yml
    secrets: inherit

  build_dt:
    name: Build demo DT
    needs: [build_cfe]
    uses: ./.github/workflows/release-build-dt.yml
    secrets: inherit
